### ISSUE TITLE
Advice for adding 2023 Escape (CAN-FD/Q4)?

### ISSUE THREAD

**Issue by northportio** [BluePilotDev/bluepilot#4]
The 2023 Escape is still considered MK4 but had a complete electronics revamp to CAN-FD. Therefore, I think (with my limited knowledge) the only way to add support for it is to treat it as a new model (ex: `23_ESCAPE_MK4_23REFRESH`)

Originally using sunnypilot, I'm able to select the Mach-E model (as that's CAN-FD) and it works about 96% of the time. The other 4% of the time I get `Controls Lagging` & `Controls Mismatch` errors.

I've added my car model to my fork but I still get errors so I'm running currently as a Mach-E. Any advice would be much appreciated.

I will install this fork and report back info in this issue.

My fingerprints file:
```python
  CAR.FORD_ESCAPE_MK4_23REFRESH: {
    (Ecu.eps, 0x730, None): [
      b'PZ11-14D003-EA\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00',
    ],
    (Ecu.abs, 0x760, None): [
      b'PZ1C-2D053-EJ\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
    ],
    (Ecu.fwdRadar, 0x764, None): [
      b'ML3T-14D049-AL\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00',
    ],
    (Ecu.fwdCamera, 0x706, None): [
      b'PJ6T-14H102-ABL\x00\x00\x00\x00\x00\x00\x00\x00\x00',
    ],
  },
```
My values file:
```python
  FORD_ESCAPE_MK4_23REFRESH = FordCANFDPlatformConfig(
    [
      FordCarDocs("Ford Escape 2023-24", hybrid=True, plug_in_hybrid=True),
      FordCarDocs("Ford Kuga 2023-24", "Adaptive Cruise Control with Lane Centering", hybrid=True, plug_in_hybrid=True),
    ],
    CarSpecs(mass=1750, wheelbase=2.71, steerRatio=16.7), #TODO check if steering ratio changed between refreshes
  )
```
[My Window Sticker (REDACTED)](https://github.com/BluePilotDev/bluepilot/files/15281169/Window.Sticker.copy.pdf)

**Comment by northportio** [comment]
Here is a route with BluePilot set as a Mach-E:
`56574443e0c3783c/2024-05-11--18-55-27`

As you can see, it is all over the road as the steering wheel still keeps trying to turn to the left after you've turned left. Using experimental mode, the car fails to initiate 90º turns. it constantly throws errors that there is not enough power to steer, even at times 20° turns.

**Comment by blue-genie** [comment]
Ford for now can't make turns with a radius smaller 50m.

I took the thing that happened around seconds 45, in this screenshot you can see the 1st graph that there are 2 spots where the graph shows  0 or 1, with very small variation, the in the 2nd graph how linear goes down and up. This is the CAN message sent over to the car. You intervened close to the end of this interval because you were about to hit the mailbox.
![image](https://github.com/BluePilotDev/bluepilot/assets/8130363/6a064362-0c24-4faf-9bed-1923a905f815)

Another view of the same section:
1st graph the orange line is what curvature OP is asking and red is what OP is sending to the car. This tells me that OP knows that it needs more curvature, but because the safety limits imposed by OP for Fords, the speed at which the curvature is changing, curvature change rate, is reaching the OP allowed limit. There are multiple places that add this type of limitation so I can't really pinpoint this code does this, but even if I could, I would not recommend changing those limits.
![image](https://github.com/BluePilotDev/bluepilot/assets/8130363/3b412d73-b4cf-489f-96a6-a88d97a601c0)

At a high level review, I think you are hitting the limit, curvature range is -0.02 to 0.02, in the graph below you can see that you are switching from one extreme to another one withing 20 seconds. OP is trying to keep up with the turns, but it can't keep up with the required curvature change rate.
![image](https://github.com/BluePilotDev/bluepilot/assets/8130363/436882fb-c56e-4d00-92af-04cfd1fd13cf)

Your car is not the only one that has this issue, it's all Fords. With only this single signal it should work fine at higher speeds and less curvy area.

I took a look at to see what is actually the "Controls Lagging" error, and based on what I see is that the OP can't run at the the desired speed, in this case 100Hz. When it drops under 90% of desired rate, you see that message - this is more of a warning, and clears itself. I looked at the PJ logs and it seems like something got stuck for a split 26.942 and 27.093, but I can't say what the device was doing.
![image](https://github.com/BluePilotDev/bluepilot/assets/8130363/70ec52db-9401-4086-9c6b-bc3674486df7)
![image](https://github.com/BluePilotDev/bluepilot/assets/8130363/9e27b473-bdb9-4a6a-bdea-97b7f49a227c)

I think you noticed that I used the "Integral", which is actually the "Derivative" to detect the change rate of a signal - I expect it to be close to 0 if the change rate is similar, like counting the seconds, if I see a jump/outlier the issue pops-up - like missing log messages -> probably process hung, or when the curvature send to the car over CAN was capped.

The issues I looked at, are not porting issues, the steer limit are normal messages in the neighborhoods at low speed, and the controls lagging is a cause of concern, but because it recovers, it's not too big, but I don't have the required knowledge to debug it further.

**Comment by northportio** [comment]
@blue-genie Thanks for the insight. I have submitted a [PR](https://github.com/BluePilotDev/bluepilot/pull/5) to add the 2023-2024 Escape. If you or someone can review that to check for errors before merging, that would be much appreciated. Thanks.

**Comment by northportio** [comment]
I've confirmed that my PR now works just about the same as the Mach-E.

@alan-polk is this something that can be merged? Thanks.

**Comment by northportio** [comment]
#5 is now merged
